image:
  repository: lbr88/domain-checker
  tag: latest
  pullPolicy: Always

domain: "example.com"
webhookUrl: "https://your-mattermost-webhook-url"
opsgenieApiKey: "b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"

schedule: "*/5 * * * *"  # Every 5 minutes

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi