apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DOMAIN: {{ .Values.domain }}
  WEBHOOK_URL: {{ .Values.webhookUrl }}
  OPSGENIE_API_KEY: {{ .Values.opsgenieApiKey }}