apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-domain-checker
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: domain-checker
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DOMAIN
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: WEBHOOK_URL
            - name: OPSGENIE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: OPSGENIE_API_KEY
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: OnFailure